# -*- coding: utf-8 -*-
"""Language build

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pMqD-XvR-UMQUiuXudseX0Y2-hCiPSk
"""

import sys
import json

# =====================
# TOKEN DEFINITIONS
# =====================

class Token:
    def __init__(self, type_, value):
        self.type = type_
        self.value = value

    def __repr__(self):
        return f"{self.type}({self.value})"


# Token Types
INTEGER = "INTEGER"
IDENTIFIER = "IDENTIFIER"
PLUS = "PLUS"
MINUS = "MINUS"
STAR = "STAR"
SLASH = "SLASH"
EQUAL = "EQUAL"
SEMICOLON = "SEMICOLON"
LPAREN = "LPAREN"
RPAREN = "RPAREN"
PRINT = "PRINT"
EOF = "EOF"


# =====================
# LEXER
# =====================

class Lexer:
    def __init__(self, text):
        self.text = text
        self.pos = 0
        self.current_char = text[self.pos] if text else None

    def advance(self):
        self.pos += 1
        self.current_char = self.text[self.pos] if self.pos < len(self.text) else None

    def skip_whitespace(self):
        while self.current_char and self.current_char.isspace():
            self.advance()

    def number(self):
        result = ""
        while self.current_char and self.current_char.isdigit():
            result += self.current_char
            self.advance()
        return Token(INTEGER, int(result))

    def identifier(self):
        result = ""
        while self.current_char and (self.current_char.isalnum()):
            result += self.current_char
            self.advance()

        if result == "print":
            return Token(PRINT, result)
        return Token(IDENTIFIER, result)

    def get_next_token(self):
        while self.current_char:

            if self.current_char.isspace():
                self.skip_whitespace()
                continue

            if self.current_char.isdigit():
                return self.number()

            if self.current_char.isalpha():
                return self.identifier()

            if self.current_char == '+':
                self.advance()
                return Token(PLUS, '+')

            if self.current_char == '-':
                self.advance()
                return Token(MINUS, '-')

            if self.current_char == '*':
                self.advance()
                return Token(STAR, '*')

            if self.current_char == '/':
                self.advance()
                return Token(SLASH, '/')

            if self.current_char == '=':
                self.advance()
                return Token(EQUAL, '=')

            if self.current_char == ';':
                self.advance()
                return Token(SEMICOLON, ';')

            if self.current_char == '(':
                self.advance()
                return Token(LPAREN, '(')

            if self.current_char == ')':
                self.advance()
                return Token(RPAREN, ')')

            raise Exception(f"Invalid character: {self.current_char}")

        return Token(EOF, None)


# =====================
# AST NODES
# =====================

class Program:
    def __init__(self, statements):
        self.statements = statements


class Assignment:
    def __init__(self, name, expr):
        self.name = name
        self.expr = expr


class Print:
    def __init__(self, expr):
        self.expr = expr


class BinaryOp:
    def __init__(self, left, op, right):
        self.left = left
        self.op = op
        self.right = right


class Integer:
    def __init__(self, value):
        self.value = value


class IdentifierNode:
    def __init__(self, name):
        self.name = name


# =====================
# PARSER
# =====================

class Parser:
    def __init__(self, lexer):
        self.lexer = lexer
        self.current_token = lexer.get_next_token()

    def eat(self, token_type):
        if self.current_token.type == token_type:
            self.current_token = self.lexer.get_next_token()
        else:
            raise Exception(f"Expected {token_type}, got {self.current_token.type}")

    def parse(self):
        statements = []
        while self.current_token.type != EOF:
            statements.append(self.statement())
        return Program(statements)

    def statement(self):
        if self.current_token.type == IDENTIFIER:
            return self.assignment()
        elif self.current_token.type == PRINT:
            return self.print_stmt()
        else:
            raise Exception("Invalid statement")

    def assignment(self):
        name = self.current_token.value
        self.eat(IDENTIFIER)
        self.eat(EQUAL)
        expr = self.expression()
        self.eat(SEMICOLON)
        return Assignment(name, expr)

    def print_stmt(self):
        self.eat(PRINT)
        expr = self.expression()
        self.eat(SEMICOLON)
        return Print(expr)

    def expression(self):
        node = self.term()
        while self.current_token.type in (PLUS, MINUS):
            op = self.current_token.value
            self.eat(self.current_token.type)
            node = BinaryOp(node, op, self.term())
        return node

    def term(self):
        node = self.factor()
        while self.current_token.type in (STAR, SLASH):
            op = self.current_token.value
            self.eat(self.current_token.type)
            node = BinaryOp(node, op, self.factor())
        return node

    def factor(self):
        token = self.current_token

        if token.type == INTEGER:
            self.eat(INTEGER)
            return Integer(token.value)

        elif token.type == IDENTIFIER:
            self.eat(IDENTIFIER)
            return IdentifierNode(token.value)

        elif token.type == LPAREN:
            self.eat(LPAREN)
            node = self.expression()
            self.eat(RPAREN)
            return node

        else:
            raise Exception("Invalid factor")


# =====================
# AST PRINTING (JSON)
# =====================

def ast_to_dict(node):
    if isinstance(node, Program):
        return {"Program": [ast_to_dict(s) for s in node.statements]}

    if isinstance(node, Assignment):
        return {"Assignment": {
            "Identifier": node.name,
            "Expression": ast_to_dict(node.expr)
        }}

    if isinstance(node, Print):
        return {"Print": ast_to_dict(node.expr)}

    if isinstance(node, BinaryOp):
        return {
            "BinaryOp": {
                "operator": node.op,
                "left": ast_to_dict(node.left),
                "right": ast_to_dict(node.right)
            }
        }

    if isinstance(node, Integer):
        return {"Integer": node.value}

    if isinstance(node, IdentifierNode):
        return {"Identifier": node.name}


# =====================
# CLI FUNCTIONS
# =====================

def run_lexer(text):
    lexer = Lexer(text)
    tokens = []

    while True:
        tok = lexer.get_next_token()
        tokens.append(tok)
        if tok.type == EOF:
            break

    for t in tokens:
        print(t)


def run_parser(text):
    lexer = Lexer(text)
    parser = Parser(lexer)
    ast = parser.parse()
    print(json.dumps(ast_to_dict(ast), indent=2))


# =====================
# MAIN (COLAB FRIENDLY)
# =====================

if __name__ == "__main__":
    sample_code = """
    x = 5;
    y = x + 2 * 3;
    print y;
    """

    print("=== TOKENS ===")
    run_lexer(sample_code)

    print("\n=== AST ===")
    run_parser(sample_code)

sample_code = "x = (3 + 4) * 5; print x;"

## simple print statement
x = 5;
print (x);

## Arithmetic + Precedence
x = 3 + 4 * 5;
print (x);

## Parentheses Override Precedence
x = (3 + 4) * 5;
print (x);

## Multiple Statements + Variables
x = 10;
y = x + 2;
z = y * 3;
print (z);

## Nested Expressions
result = (2 + 3) * (4 + 5);
print (result);

## Left Associativity
x = 10 - 3 - 2;
print (x);

## Mixed Operations
a = 20;
b = 5;
c = a / b + 3 * 2;
print (c);

## Testing for errors
print (3 + 4);

##DEMO
x = 5;
y = x * (2 + 3);
print (y);

class Interpreter:

    def __init__(self):
        self.variables = {}

    def visit(self, node):

        if isinstance(node, Program):
            result = None
            for stmt in node.statements:
                result = self.visit(stmt)
            return result

        elif isinstance(node, Assignment):
            value = self.visit(node.expr)
            self.variables[node.name] = value
            return value

        elif isinstance(node, Print):
            value = self.visit(node.expr)
            print(value)
            return value

        elif isinstance(node, Integer):
            return node.value

        elif isinstance(node, IdentifierNode):
            return self.variables[node.name]

        elif isinstance(node, BinaryOp):

            left = self.visit(node.left)
            right = self.visit(node.right)

            if node.op == "+":
                return left + right
            elif node.op == "-":
                return left - right
            elif node.op == "*":
                return left * right
            elif node.op == "/":
                return left / right
